/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paspro360 (https://sketchfab.com/paspro360)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/love-balloon-11833b0189d341b6a3173caf1a5d87f7
Title: Love Balloon
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Bloon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF( import.meta.env.BASE_URL + 'models/love_balloon.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_3">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.SteelRope}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Ferrari}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <group name="BezierCurve_1" />
                  <group name="FerrariBalloon_2" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload( import.meta.env.BASE_URL + 'models/love_balloon.glb')

