/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-muscle-car-launch-control-ready-47d7ffa796d84d1bbdebe9a007028e0e
Title: Futuristic Muscle car (Launch Control Ready)
*/

import React  from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car(props) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/futuristic_muscle_car_launch_control_ready.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.583, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Body_gameasset_Mat_1_0.geometry}
              material={materials.Body_gameasset_Mat_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Body_gameasset_Mat_2_0.geometry}
              material={materials.material_0}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Body_gameasset_Mat_5_0.geometry}
              material={materials.Body_gameasset_Mat_5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Body_gameasset_Mat_6_0.geometry}
              material={materials.Body_gameasset_Mat_6}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_FL_gameasset_Wheel_FL_gameasset_Mat_1_0.geometry}
            material={materials.Wheel_FL_gameasset_Mat_1}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_RL_gameasset_Wheel_RL_gameasset_Mat_1_0.geometry}
            material={materials.Wheel_RL_gameasset_Mat_1}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_FR_gameasset_Wheel_FR_gameasset_Mat_1_0.geometry}
            material={materials.Wheel_FR_gameasset_Mat_1}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_RR_gameasset_Wheel_RR_gameasset_Mat_1_0.geometry}
            material={materials.Wheel_RR_gameasset_Mat_1}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/futuristic_muscle_car_launch_control_ready.glb')