/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Cloud({color , opacity, ...props }) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + "models/cloud.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          transparent
          opacity={opacity}
          color={color}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "models/cloud.glb");