/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jasonin10 (https://sketchfab.com/jasonin10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/test-middle-finger-d690519cefbd49e4956610d5dd1a267a
Title: Test Middle Finger
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Midfing (props) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL +  'models/midfing.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/midfing.glb')
